# Generated by Django 5.1.3 on 2025-08-03 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='expiry_date',
        ),
    ]
