# Generated by Django 5.1.3 on 2025-08-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0002_remove_medicine_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[], max_length=10),
        ),
    ]
