# Generated by Django 5.1.3 on 2025-08-18 18:47

import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0003_alter_patient_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='date',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='follow_up_instructions',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insurance_policy_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='insurance_provider',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.CreateModel(
            name='LabOders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sample_collected', 'Sample Collected'), ('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='sample_collected', max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratories', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratories', to='hms.patient')),
            ],
        ),
        migrations.CreateModel(
            name='labResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='hms.laboders')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='hms.patient')),
            ],
        ),
    ]
