# Generated by Django 5.1.3 on 2025-08-27 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0006_appointments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='date',
        ),
    ]
