# Generated by Django 5.1.3 on 2025-08-27 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0007_remove_appointments_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointments',
        ),
    ]
