# Generated by Django 5.1.3 on 2025-08-27 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0009_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labresults',
            name='lab_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results_order', to='hms.laboders'),
        ),
        migrations.AlterField(
            model_name='labresults',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results_patient', to='hms.laboders'),
        ),
    ]
