# Generated by Django 5.1.3 on 2025-08-27 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0010_alter_labresults_lab_order_alter_labresults_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labresults',
            name='patient',
        ),
        migrations.AlterField(
            model_name='labresults',
            name='lab_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LabOrder', to='hms.laboders'),
        ),
    ]
