# Generated by Django 5.1.3 on 2025-08-27 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0011_remove_labresults_patient_alter_labresults_lab_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
