# Generated by Django 5.1.3 on 2025-09-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0013_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('not_paid', 'Not Paid')], default='not_paid', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('not_paid', 'Not Paid')], default='not_paid', max_length=10),
        ),
    ]
