# Generated by Django 5.1.3 on 2025-09-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0014_appointments_payment_status_patient_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('pharmacist', 'Pharmacist'), ('receptionist', 'Receptionist')], default='admin', max_length=15),
        ),
    ]
