# Generated by Django 5.1.3 on 2025-09-26 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0017_alter_laboders_tests_alter_labresults_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labresults',
            name='lab_order',
        ),
        migrations.DeleteModel(
            name='LabOders',
        ),
        migrations.DeleteModel(
            name='labResults',
        ),
    ]
