# Generated by Django 5.1.3 on 2025-09-26 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0018_remove_labresults_lab_order_delete_laboders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabOders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tests', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sample_collected', 'Sample Collected'), ('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='sample_collected', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratories', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratories', to='hms.patient')),
            ],
        ),
        migrations.CreateModel(
            name='LabResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LabOrder', to='hms.laboders')),
            ],
        ),
    ]
