# Generated by Django 4.2.25 on 2025-11-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0021_alter_sale_date_alter_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnChainAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.IntegerField(db_index=True)),
                ('record_hash', models.CharField(db_index=True, help_text='0x prefixed sha256 hex', max_length=66)),
                ('tx_hash', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='appointments',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.RemoveField(
            model_name='laboders',
            name='notes',
        ),
    ]
