# Generated by Django 4.2.25 on 2025-11-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0022_onchainaudit_alter_appointments_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onchainaudit',
            name='record_cid',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
