# Generated by Django 4.2.25 on 2026-01-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0023_onchainaudit_record_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='blockchain_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of diagnosis record', max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, help_text='Transaction hash on blockchain', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labresults',
            name='blockchain_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of lab results record', max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='labresults',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, help_text='Transaction hash on blockchain', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='blockchain_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of patient record', max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, help_text='Transaction hash on blockchain', max_length=100, null=True),
        ),
    ]
