# Generated by Django 4.2.25 on 2026-01-11 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0024_diagnosis_blockchain_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboders',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laboratories', to=settings.AUTH_USER_MODEL),
        ),
    ]
